theme: minima
title: Zee | Professional Logbook
email: zahra.nur.ahmad@outlook.com
description: A living resume translating a dynamic career in software consultancy into clear technical skill narratives.
